package com.codeops.courier.entity.enums;

public enum AuthType {
    NO_AUTH, API_KEY, BEARER_TOKEN, BASIC_AUTH,
    OAUTH2_AUTHORIZATION_CODE, OAUTH2_CLIENT_CREDENTIALS,
    OAUTH2_IMPLICIT, OAUTH2_PASSWORD,
    JWT_BEARER, INHERIT_FROM_PARENT
}
